---
title: "ECO634_Lab01"
author: "Megan Mitchell"
date: "9/14/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1.  Explain why the outputs of the two lines are different.

    * The outputs of the two lines are different because these are two different variables in R. The one code              without quotations is a numeric vector because it is a numerical value and the code with quotation marks is a         character vector because it is a string value,. 


2.Is c_1 a variable, or a function? How do you know?

    * C_1 is a function instead of a value because it specifies a named parameter and is visible in the Rstudio         environment 


3.Is c_2 a variable, or a function? How do you know?

    * C_2 is also a function for the same reasons as #2
  

4. If c_1 and c_2 have different values, why?


   * C_1 and C_2 have different values because c_1 is numerical whereas c_2 is a character vector with string data.


5. What are the dimensions of the matrix (i.e. how many rows and columns)?


   * there are 3 rows and 2 columns in the matrix

    my_vec <- c(1:3)
    my_vec
    mat_1 = matrix(my_vec)
    mat_1
  

6. Write R code to retrieve the element of mat_1 that has a value of 3.


  * mat_1[3]
  

7. Paste the code you used to create mat_2.


  * my_vec <- c(1:3)
  mat_2 = matrix(my_vec, byrow= TRUE, nrow=2)
  mat_2


8. Paste the code you used to create mat_3.


  * my_vec <- c(1:3)
    mat_3 = matrix(my_vec, byrow= TRUE, nrow=3)
    mat_3


9. Did R use rows or columns to recycle the values in my_vec?


  * R used rows to recycle the values in my_vec


10. Create a matrix, mat_4, with a number of elements that is not a multiple of 3 and paste the code into your report.


  * my_vec <- c(1,4,14,17)
    mat_4 = matrix(my_vec, byrow= TRUE, nrow=3)
    mat_4


11.  How did R handle the recycling of values of my_vec in mat_4?


  * R recycled the elements with the lowest values in my_vec 


12. For each of the 8 lines, answer the following: A. Did the line return a 1: value, 2: error, or 3: NULL? B. If it did not return an error, what type of subsetting operation was used? C. If it did not return an error, explain how R chose which element to retrieve.


  * line 1: Returned a value. The "[[]]" subsetting operator was used to extract elements from the list. 

    line 2: Returned a value. The "[[]]" subsetting operator was used to extract elements from the list.                The "as.numeric" operation told R to only return a numeric value.

    line 3: Returned a NULL.

    line 4: Returned a string value (text in quotation marks). The "[[]]" subsetting operator was used to extract         the element named "one" from the list. The element named "one" corresponds to the string data "five point         two". 

    line 5: Returned a string value (text in quotation marks). The "$" operator was used to extract the element         named "one" from the list, which corresponds to the string data "five point two"

    line 6:  Returned a string value (text in quotation marks). The "$" operator was used to extract the element        named one (not a string because no quotations) from the list, which corresponds to the string data "five point        two"

    line 7: Returned an error (unexpected numeric constant in "my_list_1$1"

    line 8: Returned a NULL
  
    codes for answering #12

    my_list_1 <- list(5.2, "five point two", 0:5)
   
    names(my_list_1) <- c("two", "one", "three")
   
    my_list_1

    my_list_1[[1]]
    my_list_1[[as.numeric("1")]]
    my_list_1[["1"]]
    my_list_1[["one"]]
    my_list_1$one
    my_list_1$"one"
    my_list_1$1
    my_list_1$"1"


13.  Identify which lines produced output "five point two" and explain why.


    * Lines 4, 5, &6 produced the output "five point two". They produced this output because we asked R to extract        the element named "one", which equals the string value "five point two"


14.Identify which lines produced NULL output and explain why.

    * Lines 3 and 8 produced the output NULL, which means the elements contained an undefined value or was missing        data. This is because there was no element named "1", it was named "one". If there was no quotations around         "1", R would have extracted the first element (1) in the list.

   






